### PR TITLE
Made axios work

### PR DESCRIPTION
**Pull request by Adesin-fr**
The error seems to come from the Connector not having a constructor, and maybe some other fixes I've done, don't remember fully... ;)

### CODE REVIEW

**Comment by leob** [comment]
> The error seems to come from the Connector not having a constructor, and maybe some other fixes I've done, don't remember fully... ;)

@Adesin-fr Okay thanks, let me try that ... yes it was indeed complaining about `Connection` having no constructor.

**Comment by leob** [comment]
> The error seems to come from the Connector not having a constructor, and maybe some other fixes I've done, don't remember fully... ;)

@Adesin-fr When I pull down the code and I do an `npm install` or an `npm run build`, I'm still getting these warnings:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
axios (imported by js-src/Websocket.ts)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
axios (guessing 'axios')
created ./dist/laravel-echo-api-gateway.js, ./dist/laravel-echo-api-gateway.common.js, ./dist/laravel-echo-api-gateway.iife.js in 1.1s
```

But in the end it did create the output JS files - so yeah, maybe it's okay - I'm going to check if the build works in Github ...

**Comment by Adesin-fr** [comment]
Yeah I saw this. 
Don't know why, but it seems axios version is pretty old, and ditching it for pure fetch calls would surely remove those errors !

**Comment by leob** [comment]
> Yeah I saw this. Don't know why, but it seems axios version is pretty old, and ditching it for pure fetch calls would surely remove those errors !

@Adesin-fr We tried that already but that wasn't a big success, we reverted that ... no we're keeping Axios, I'm trying to get the import working now.

**Comment by leob** [comment]
I'm closing this PR because I made a follow-up PR (https://github.com/georgeboot/laravel-echo-api-gateway/pull/37) ... I'm also trying to replace yarn by npm, I find it pretty annoying to "mix" the two all the time, I just want npm only.

**Comment by leob** [comment]
> I'm closing this PR because I made a follow-up PR (#37) ... I'm also trying to replace yarn by npm, I find it pretty annoying to "mix" the two all the time, I just want npm only.

@Adesin-fr I took your PR, then used that to create a new PR, messed around with it, got rid of `yarn` and replaced it by `npm`, messed around a bit more, and now finally the build and the npm-publish seems successful - yay !

I'm now going to test it with our app, let's keep our fingers crossed ... :)

**Pull request closed without merging**
