### PR TITLE
Better connection lost handling

### PR DESCRIPTION
**Pull request by Adesin-fr**
There are some issues with the current version : 

- Before this, if there were no internet connection on first connect, it would fail and did not retry. That use-case is now handled.
- After a connection failure, channels were not re-subscribed. That is now fixed.
- The "Ping" interval was triggered everytime we did tried to connect, even without success. So if we tried to connect 40x, we would have 40 "setInterval" triggered, and 40x ping/minute , instead of one !

That's a bit more production-ready now :)

### CODE REVIEW

**Comment by Adesin-fr** [comment]
@leob I think you should have a look at this ;)
Since I'm using this in a 24/24 connected machine, I had to check it would survive rude conditions.
And it seems some of theme weren't ready enough for prod. 
So I fixed them !

My WIFI ON/OFF switch had a hard time, being switched back-forth for a while ;)

**Comment by leob** [comment]
> @leob I think you should have a look at this ;) Since I'm using this in a 24/24 connected machine, I had to check it would survive rude conditions. And it seems some of theme weren't ready enough for prod. So I fixed them !
> 
> My WIFI ON/OFF switch had a hard time, being switched back-forth for a while ;)

@Adesin-fr Thanks, will check it out !

**Comment by Adesin-fr** [comment]
First, thanks for having merged this.

That's strange since I don't think it should not break private channels ...

To see "trying to connect" messages and others , you must enable debug mode on the Echo instruction (remember the last dockbloc of the readme ?)

I'll have a look at this with private channels later today :)

**Comment by leob** [comment]
> First, thanks for having merged this.
> 
> That's strange since I don't think it should not break private channels ...
> 
> To see "trying to connect" messages and others , you must enable debug mode on the Echo instruction (remember the last dockbloc of the readme ?)
> 
> I'll have a look at this with private channels later today :)

@Adesin-fr Yes, I did enable the debug option, otherwise I wouldn't have seen the messages which I saw ... so, I do see some messages, but I'm not seeing all of the messages that I would expect to see :)

Thanks for looking at it! If you can't find anything then let me know, and I'll put a bit more effort into debugging it ...

**Comment by leob** [comment]
@Adesin-fr P.S. please don't forget to pull `master` before you start working on it - I've pushed a commit 1 minute ago ...

**Comment by Adesin-fr** [comment]
I've tried to have a look. 
I'd like to push my project to a staging env with the 0.5.2 version, but it missed axios  (seems you removed it some commits ago !!)

In my project, I'm seeing the "trying to connect messages and every others. 
Are you sure you correctly imported Echo in your project ?

**Comment by leob** [comment]
@Adesin-fr I was trying to debug my websocket issues - what was just baffling was that when I opened our app in two browsers (Chrome and Firefox) and logged in in both browser windows, I could send a message (via websockets) from "Chrome" to "Firefox", but not the other way around (from "Firefox" to "Chrome") !

Debugging it was an ordeal (I had a hard time to even log anything to CloudWatch), but what I did see was this - a "410 Gone" exception from API Gateway:

```
[2024-12-07 10:57:01] DEBUG: Preparing to send to connections for channel .........
[2024-12-07 10:57:01] DEBUG: Sending message to connection 'CascQeh7oAMCJLw='
[2024-12-07 10:57:01] DEBUG: Sending message to connection 'K8gVIdmDIAMCLIA='
[2024-12-07 10:57:02] ERROR:  MESSAGE ###### MessageService@sendNotification - exception - error: Error executing "PostToConnection" on "https://..............."; AWS HTTP error: Client error: `POST https://...........` resulted in a `410 Gone` response Unable to parse error information from response - Error parsing JSON: Syntax error[#0 /var/task/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(98): Aws\WrappedHttpHandler->parseError()
```

So, sending the message to the first connection worked, but sending it to the second connection failed with a "410 Gone" ...

And that gave me an idea - "let's look in the Connections table in DynamoDB" - and bingo! When I cleared that table, things started to work ...

Pretty clear that there are sometimes "stale" connections left behind in that table - which is strange, because we DO have this piece of code in the `catch` block in `ConnectionRepository::sendMessage`:

```
if ($e->getAwsErrorCode() === 'GoneException') {
  $this->subscriptionRepository->clearConnection($connectionId);

  return;
}
```

So the idea is that in case of an HTTP 410 Gone" it SHOULD remove that connection from the DynamoDB table ... strange that that doesn't always seem to work.

This still looks like a potential weakness - the fact that the Connections table can contain "stale" connections ... I mean, in theory "it should just work", but it feels somewhat fragile (potentially).

P.S. I was also struggling with getting any logging to work - I cloned the repo (`laravel-api-gateway`) and then I made changes locally (I added log statements in the PHP code), and I linked to the local directory in my app's `composer.json`, like this:

```
    "repositories": [
      {
          "type": "path",
          "url": "../laravel-echo-api-gateway"
      }
    ],
```

and then with:

```
"georgeboot/laravel-echo-api-gateway": "dev-master",
```

but it seemed to just **refuse** to pick up the dependency from my local folder - I did NOT get to see any of the logging that I added in the PHP code - **somehow** it did not seem to use the "local" version, but the version from Github ... ?

And to top it all off I had issues with the AWS S3 file adapter because of the upgraded `aws-sdk-php` version - it threw this exception when trying to fetch a file from S3:

```
Invalid configuration value provided for "token". Expected Aws\Token\TokenInterface|Aws\CacheInterface|array|bool|callable, but got string
```

Apparently that requires a PHP fix/upgrade:

https://github.com/aws/aws-sdk-php/issues/2567#issuecomment-1318388251
https://github.com/laravel/framework/pull/44979

**Comment by Adesin-fr** [comment]
Well I did not yet experienced the 410 errors !

We'll surely need to address it soon !

**Comment by leob** [comment]
> Well I did not yet experienced the 410 errors !
> 
> We'll surely need to address it soon !

@Adesin-fr I've seen that quite often in our app, but today I found out what apparently causes it: "stale" connections in the DynamoDB "Connections" table! That **should** never happen, but apparently it did ... clearing the table solved the issue.

**Comment by leob** [comment]
> Well I did not yet experienced the 410 errors !
> 
> We'll surely need to address it soon !

@Adesin-fr Look at this change from another PR (https://github.com/georgeboot/laravel-echo-api-gateway/pull/25):

image

Maybe this change makes it more robust - checking for 

```
e->getStatusCode() === Response::HTTP_GONE || $e->getAwsErrorCode() === 'GoneException'
```

instead of ONLY for `e->getAwsErrorCode() === 'GoneException'` ...

This could be a reason why in some cases the "stale" connection isn't getting cleared.

**Comment by leob** [comment]
@Adesin-fr So, after upgrading my app to the latest version of `laravel-echo-api-gateway` (with the `import axios` statement), I was getting this:

image

But, it was easy to fix - I had to remove this line from my frontend app's initialization code:

```
window.axios.defaults.headers.common['Authorization'] = 'Bearer ' + token;
```

and instead I had to pass the `bearerToken` option to `Echo`:

```
window.Echo = new Echo({
  authEndpoint: ....................,
  bearerToken: token,
  broadcaster,
  host,
  debug: isStaging === true
});
```

Works now!

**Pull request merged**
