### PR TITLE
Handling websocket disconnects

### PR DESCRIPTION
**Pull request by Adesin-fr**
This PR adds code for frontend to #2  handle connections issues : disconnections, not being able to connect, automatically reconnect...

It also adds Bref 2.0 as a supported version (NB: in Bref 2.0, serverless.yml syntax changed a bit. See documentation...)

### CODE REVIEW

**Comment by leob** [comment]
@Adesin-fr Thanks, will review/merge today!

**Comment by leob** [comment]
@Adesin-fr Okay, I browsed the code changes a bit (not extensively yet, will do that later) - do I understand correctly that, whenever the connection (socket) gets closed, it will automatically attempt to reopen (reconnect) itself? Would that mean that a connection could never be closed (even if we wanted to), or am I misunderstanding that?

**Comment by Adesin-fr** [comment]
If you call the close() method of the broadcast driver, it will be gracefully closed.
And when the browser tab is closed, connections and JS code are cleaned too...

**Comment by georgeboot** [comment]
Maybe remove the `console.log()` calls

**Comment by Adesin-fr** [comment]
That's what I was thinking also. 
Some were there before me, I might have forgot some of mines ;)
But for sure, it's too verbose ;)

Perhaps add a "debug" option that would allow to enable logging ??
Not sure how that should be handled TBH...

**Comment by Adesin-fr** [comment]
Just removed logs, Only kept 2 logs that are triggered when : 
- subscribing on private channel
- parsing a message as json

**Comment by leob** [comment]
@Adesin-fr I think it looks good, but the `console.log` messages (most of which are gone now) might be useful in some circumstances? @georgeboot What about the idea of a `debug` option as @Adesin-fr already mentioned?

**Comment by georgeboot** [comment]
Yeah debug sounds good

**Comment by Adesin-fr** [comment]
It seems this commit does the trick. At least on tests. 
I still have to check that Echo doesn't filters the .debug property of the options object, but it doesn't seem !

PS : Making a last commit to update the readme also...

**Comment by leob** [comment]
@Adesin-fr Thanks, nice one ... will review and then merge (if all looks fine) !

**Comment by leob** [comment]
> Hi,
> 
> Will you merge this soon ? I have a project where a machine needs to be connected 24/24 and I need this feature ;)

@Adesin-fr Okay let me merge it tonight and then test it with our app, and I'll let you know ...

**Comment by Adesin-fr** [comment]
Nice ;)
I think we must also update the version in package.json so npmjs will pick this update ?

**Comment by leob** [comment]
> Nice ;) I think we must also update the version in package.json so npmjs will pick this update ?

@Adesin-fr I know, I'm trying that - I've created a new release (0.5.1) and clicked "publish", but publishing to npmjs fails:

_Run `yarn publish --access public --tag latest`_
........................
_error Couldn't publish package: "https://registry.npmjs.org/laravel-echo-api-gateway: Not found"_

This is my 3rd attempt and previously I got a different "yarn" error, but now it just keeps saying "not found ...

Before this last error I'm seeing a ton of warnings, but I don't know if that's the cause of the above or just "warnings":

_npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1731603326585-0.19912559614290437/node but npm is using /opt/hostedtoolcache/node/12.22.12/x64/bin/node itself_

_axios (imported by js-src/Websocket.ts)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
axios (guessing 'axios')_

and so on ...

At some point I just deleted the `0.5.1` release and tag, redid the whole thing with `0.5.2` (not sure if that was actually a good idea), but now in the `yarn publish --access public --tag latest` run I'm seeing that it's still referencing `0.5.1` instead of `0.5.2` ...

Bit of a mess and I'm mainly in "trial and error" mode now ... who has got the brilliant idea to make this thing work?

**Comment by leob** [comment]
@Adesin-fr Okay yet another attempt and then I'm off to bed and we'll see tomorrow ......

**Comment by leob** [comment]
@Adesin-fr Wait lol it was staring me in the face:

_"(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
axios (imported by js-src/Websocket.ts)"_

"Unresolved dependencies ... axios" - I guess this is what it's tripping over ...

**Comment by leob** [comment]
@Adesin-fr "Fixed" a number of things, deleted tag/release, created new one, _"Unresolved dependencies ... axios"_ is gone now - however, stil getting this error in Github's "publish" action:

_"error Couldn't publish package: "[registry.npmjs.org/laravel-echo-api-gateway](https://registry.npmjs.org/laravel-echo-api-gateway): Not found"_

I'm getting a bit desperate now, running out of ideas ... will have a fresh look tomorrow.

**Comment by leob** [comment]
@Adesin-fr Discussing with the other contributor on the other PR thread, maybe he has a clue ... there are still 2 things I could try, long shot but I don't have any other ideas left ;-)

**Comment by leob** [comment]
@georgeboot Can you help me out? I think I'm unable to resolve this myself - I'm trying to publish a new release:

https://github.com/georgeboot/laravel-echo-api-gateway/releases/tag/0.5.1

but the Github "publish" action keeps failing at "yarn publish" (`yarn publish --access public --tag latest`) - see:

https://github.com/georgeboot/laravel-echo-api-gateway/actions/runs/11869630146/job/33080163251

image

It's unable to publish to `npmjs` ... I added `--verbose` to `yarn publish` to get more detail, and then it shows the HTTP 404 - I then googled that and found some pointers:

https://stackoverflow.com/questions/39115101/getting-404-when-attempting-to-publish-new-package-to-npm

and this one:

https://github.com/npm/cli/issues/1637

These make me believe that the most likely cause is that there might be something wrong with the NPM token in our "Github secrets" ... re you able to check 

image

**Comment by georgeboot** [comment]
I think it should be fixed now.

https://www.npmjs.com/package/laravel-echo-api-gateway

The token was not expired but it was a legacy style token. Replaced it now with a fine grained one, that seemed to do the job.

**Comment by leob** [comment]
@georgeboot Thanks, that's brilliant - and I think the "publish" is done now (I guess you did it?) - because I tried to re-trigger the job and then I got `You cannot publish over the previously published versions: 0.5.1."` ... 

Yes that seems to be the case: `0.5.1 • Public • Published 2 hours ago` (on https://www.npmjs.com/package/laravel-echo-api-gateway)

All good then!

**Pull request merged**
